Trying:
    add_integer = __import__('0-add_integer').add_integer
Expecting nothing
ok
Trying:
    add_integer(1, 2)
Expecting:
    3
ok
Trying:
    add_integer(100, -2)
Expecting:
    98
ok
Trying:
    add_integer(2.1)
Expecting:
    100
ok
Trying:
    add_integer(100.3, -2)
Expecting:
    98
ok
Trying:
    add_integer(4, "School")
Expecting:
    Traceback (most recent call last):
              ...
    TypeError: b must be an integer
**********************************************************************
File "./tests/0-add_integer.txt", line 27, in 0-add_integer.txt
Failed example:
    add_integer(4, "School")
Expected:
    Traceback (most recent call last):
              ...
    TypeError: b must be an integer
Got:
    Traceback (most recent call last):
      File "/usr/lib/python3.8/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 0-add_integer.txt[5]>", line 1, in <module>
        add_integer(4, "School")
      File "/alx-higher_level_programming/0x07-python-test_driven_development/0-add_integer.py", line 17, in add_integer
        raise TypeError("a must be an integer")
    TypeError: a must be an integer
Trying:
    add_integer(None)
Expecting:
    Traceback (most recent call last):
              ...
    TypeError: a must be an integer
ok
Trying:
    add_integer('1', 1)
Expecting:
    Traceback (most recent call last):
              ...
    TypeError: a must be an integer
ok
Trying:
    add_integer('2', '1')
Expecting:
    Traceback (most recent call last):
              ...
    TypeError: a must be an integer
ok
Trying:
    add_integer((1, 1))
Expecting:
    Traceback (most recent call last):
              ...
    TypeError: a must be an integer
ok
Trying:
    add_integer(123, [])
Expecting:
    Traceback (most recent call last):
              ...
    TypeError: b must be an integer
**********************************************************************
File "./tests/0-add_integer.txt", line 57, in 0-add_integer.txt
Failed example:
    add_integer(123, [])
Expected:
    Traceback (most recent call last):
              ...
    TypeError: b must be an integer
Got:
    Traceback (most recent call last):
      File "/usr/lib/python3.8/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 0-add_integer.txt[10]>", line 1, in <module>
        add_integer(123, [])
      File "/alx-higher_level_programming/0x07-python-test_driven_development/0-add_integer.py", line 17, in add_integer
        raise TypeError("a must be an integer")
    TypeError: a must be an integer
Trying:
    add_integer("Hello")
Expecting:
    Traceback (most recent call last):
              ...
    TypeError: a must be an integer
ok
Trying:
    add_integer(2.9, 2.9)
Expecting:
    4
ok
Trying:
    add_integer(-1)
Expecting:
    97
ok
Trying:
    add_integer(float('inf'), 0)
Expecting:
    Traceback (most recent call last):
              ...
    OverflowError: cannot convert float infinity to integer
ok
Trying:
    add_integer(float('inf'), float('-inf'))
Expecting:
    Traceback (most recent call last):
              ...
    OverflowError: cannot convert float infinity to integer
ok
Trying:
    add_integer(0, float('nan'))
Expecting:
    Traceback (most recent call last):
              ...
    ValueError: cannot convert float NaN to integer
ok
**********************************************************************
1 items had failures:
   2 of  17 in 0-add_integer.txt
17 tests in 1 items.
15 passed and 2 failed.
***Test Failed*** 2 failures.
Trying:
    add_integer = __import__('0-add_integer').add_integer
Expecting nothing
ok
Trying:
    add_integer(1, 2)
Expecting:
    3
ok
Trying:
    add_integer(100, -2)
Expecting:
    98
ok
Trying:
    add_integer(2.1)
Expecting:
    100
ok
Trying:
    add_integer(100.3, -2)
Expecting:
    98
ok
Trying:
    add_integer(4, "School")
Expecting:
    Traceback (most recent call last):
              ...
    TypeError: b must be an integer
**********************************************************************
File "./tests/0-add_integer.txt", line 27, in 0-add_integer.txt
Failed example:
    add_integer(4, "School")
Expected:
    Traceback (most recent call last):
              ...
    TypeError: b must be an integer
Got:
    Traceback (most recent call last):
      File "/usr/lib/python3.8/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 0-add_integer.txt[5]>", line 1, in <module>
        add_integer(4, "School")
      File "/alx-higher_level_programming/0x07-python-test_driven_development/0-add_integer.py", line 17, in add_integer
        raise TypeError("a must be an integer")
    TypeError: a must be an integer
Trying:
    add_integer(None)
Expecting:
    Traceback (most recent call last):
              ...
    TypeError: a must be an integer
ok
Trying:
    add_integer('1', 1)
Expecting:
    Traceback (most recent call last):
              ...
    TypeError: a must be an integer
ok
Trying:
    add_integer('2', '1')
Expecting:
    Traceback (most recent call last):
              ...
    TypeError: a must be an integer
ok
Trying:
    add_integer((1, 1))
Expecting:
    Traceback (most recent call last):
              ...
    TypeError: a must be an integer
ok
Trying:
    add_integer(123, [])
Expecting:
    Traceback (most recent call last):
              ...
    TypeError: b must be an integer
**********************************************************************
File "./tests/0-add_integer.txt", line 57, in 0-add_integer.txt
Failed example:
    add_integer(123, [])
Expected:
    Traceback (most recent call last):
              ...
    TypeError: b must be an integer
Got:
    Traceback (most recent call last):
      File "/usr/lib/python3.8/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 0-add_integer.txt[10]>", line 1, in <module>
        add_integer(123, [])
      File "/alx-higher_level_programming/0x07-python-test_driven_development/0-add_integer.py", line 17, in add_integer
        raise TypeError("a must be an integer")
    TypeError: a must be an integer
Trying:
    add_integer("Hello")
Expecting:
    Traceback (most recent call last):
              ...
    TypeError: a must be an integer
ok
Trying:
    add_integer(2.9, 2.9)
Expecting:
    4
ok
Trying:
    add_integer(-1)
Expecting:
    97
ok
Trying:
    add_integer(float('inf'), 0)
Expecting:
    Traceback (most recent call last):
              ...
    OverflowError: cannot convert float infinity to integer
ok
Trying:
    add_integer(float('inf'), float('-inf'))
Expecting:
    Traceback (most recent call last):
              ...
    OverflowError: cannot convert float infinity to integer
ok
Trying:
    add_integer(0, float('nan'))
Expecting:
    Traceback (most recent call last):
              ...
    ValueError: cannot convert float NaN to integer
ok
**********************************************************************
1 items had failures:
   2 of  17 in 0-add_integer.txt
17 tests in 1 items.
15 passed and 2 failed.
***Test Failed*** 2 failures.
